"""Generate a markdown summary from tests/test_manifest.json."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = REPO_ROOT / "tests" / "test_manifest.json"
OUTPUT_PATH = REPO_ROOT / "docs" / "test-manifest-summary.md"
LANE_ORDER = ("fast", "core", "heavy", "benchmark", "research")


def _load_manifest() -> dict[str, dict[str, str]]:
    data = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    files = data.get("files", {})
    if not isinstance(files, dict):
        raise ValueError("tests/test_manifest.json must contain a top-level 'files' object")
    return files


def render_manifest_report() -> str:
    files = _load_manifest()

    lane_to_files: dict[str, list[str]] = defaultdict(list)
    bundle_to_files: dict[str, list[str]] = defaultdict(list)

    for filename, meta in sorted(files.items()):
        lane = meta["lane"]
        bundle = meta["bundle"]
        lane_to_files[lane].append(filename)
        bundle_to_files[bundle].append(filename)

    bundle_groups: dict[str, list[str]] = defaultdict(list)
    for bundle in sorted(bundle_to_files):
        prefix = bundle.split("-", 1)[0]
        bundle_groups[prefix].append(bundle)

    lines = [
        "# Test Manifest Summary",
        "",
        "> Generated from `tests/test_manifest.json` by `python tools/dev/generate_test_manifest_report.py`.",
        "> Do not edit this file by hand.",
        "",
        "## Lane Inventory",
        "",
        "| Lane | File count | Files |",
        "|---|---:|---|",
    ]

    for lane in LANE_ORDER:
        filenames = lane_to_files.get(lane, [])
        file_list = ", ".join(f"`{name}`" for name in filenames)
        lines.append(f"| `{lane}` | {len(filenames)} | {file_list} |")

    lines.extend(
        [
            "",
            "## Bundle Inventory",
            "",
            "| Bundle | File count | Files |",
            "|---|---:|---|",
        ]
    )

    for group in LANE_ORDER:
        for bundle in bundle_groups.get(group, []):
            filenames = bundle_to_files[bundle]
            file_list = ", ".join(f"`{name}`" for name in filenames)
            lines.append(f"| `{bundle}` | {len(filenames)} | {file_list} |")

    return "\n".join(lines) + "\n"


def main() -> int:
    OUTPUT_PATH.write_text(render_manifest_report(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
